# Server Configuration
server:
  host: device-metrics.onrender.com
  port: 443
  pc_metrics_endpoint: https://device-metrics.onrender.com/metrics
  esp32_metrics_endpoint: https://device-metrics.onrender.com/esp32metrics
  protocol: https

# Client Configuration
client:
  device_name_prefix: metrics-device
  metrics_interval_seconds: 10
  max_retry_attempts: 3
  retry_delay_seconds: 1

# Logging Configuration
logging:
  level: INFO
  file: 
    enabled: true
    path: logs/application.log
  console:
    enabled: true

# Database Configuration
database:
  type: sqlite
  path: data.db